name: Java CI

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Validate Gradle wrapper
      - run: ./gradlew clean build --stacktrace
      - run: ./gradlew codeCoverageReport

      - uses: codecov/codecov-action@v2
      - name: Codecov
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./build/reports/jacoco/report.xml
          verbose: true
          fail_ci_if_error: true
